[Fix] failed unit test (#420)
* fix TypeError: BaseQuantLinear.__init__() missing 1 required positional argument: 'outfeatures'

* fix assert error

* BITBLAS now supports saving as shard file

* fix assert error

* Fixed the error of loading marlin format model